# Generated by Django 4.2.1 on 2023-05-26 06:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('phone', models.IntegerField(default=0)),
                ('telephone_number', models.IntegerField(default=0)),
                ('fax_number', models.IntegerField(default=0)),
                ('email_id', models.EmailField(max_length=254)),
                ('account_created', models.DateField(default=datetime.datetime.now)),
                ('image_upload', models.ImageField(null=True, upload_to='images')),
                ('qr_code', models.ImageField(null=True, upload_to='qrcode')),
                ('social_media1', models.CharField(max_length=100, null=True)),
                ('social_media2', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp_detail.roles')),
            ],
        ),
    ]
