# Generated by Django 4.2.1 on 2023-06-05 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_detail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='image_upload',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='qr_code',
            field=models.ImageField(null=True, upload_to='qrcode/'),
        ),
    ]
